package xyz.coolsa.biosphere;

public enum BiospheresStructureFamily {
	VILLAGE,
	PILLAGER_OUTPOST,
	WOODLAND_MANSION,
	ANCIENT_CITY,
	STRONGHOLD,
	TRIAL_CHAMBERS,
	OCEAN_MONUMENT,
	OCEAN_RUIN,
	MINESHAFT,
	RUINED_PORTAL,
	TRAIL_RUINS,
	DESERT_PYRAMID,
	JUNGLE_TEMPLE,
	IGLOO,
	SWAMP_HUT
}
